### ISSUE TITLE
This version of ChromeDriver only supports Chrome version 

### ISSUE THREAD

**Issue by CustomNPC** [Not-swasd/Novoline-bot-by-swasd#2]
This version of ChromeDriver only supports Chrome version 같은오류가뜹니다..... 어떡개고쳐요?

![스크린샷 2022-08-13 오후 2 51 43](https://user-images.githubusercontent.com/67010072/184470678-f6db1f92-ad06-4860-8281-32b265587233.png)

**Comment by Not-swasd** [comment]
지원 x
